### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn'

### ISSUE THREAD

**Issue by KishorJena** [nishitpatel01/fake_news_detection_dev#21]
```console
Traceback (most recent call last):
  File "prediction.py", line 28, in <module>
    detecting_fake_news(var)
  File "prediction.py", line 19, in detecting_fake_news
    load_model = pickle.load(open('final_model.sav', 'rb'))
ModuleNotFoundError: No module named 'sklearn'
```

```bash
Package       Version
------------- -------
joblib        1.1.0
numpy         1.22.3
pip           22.0.4
scikit-learn  1.0.2
scipy         1.8.0
setuptools    58.1.0
threadpoolctl 3.1.0

**Comment by mahsanghani** [comment]
pip3 install sklearn

**Comment by mahsanghani** [comment]
conda install sklearn
